### ISSUE TITLE
Will e-book or PDF ever be available?

### ISSUE THREAD

**Issue by hieu-van** [treeman/why_cryptocurrencies#63]

**Comment by treeman** [comment]
Hi!

Sorry, I've been having a bunch of personal issues that have severely delayed the e-book and PDF. I've been depressed and burnt out, and also recently gotten our third kid.

But I will work on it this spring so unless something similar comes up again, they should be done before summer.

Thank you for your interest.

**Comment by hieu-van** [comment]
I'm sorry to hear that, man. I hope everything will be alright for you soon. I've found your book a long time ago and I'm very much impressed with it. Please keep up the good work!

**Comment by celtic-coder** [comment]
Hi Jonas (@treeman),

First, congratulations on the birth of your daughter! I'm sure that your hands are full, but this is a special time when the children are young. You are probably not appreciating it right now, with restricted sleep and all the pressures that children bring, but do "step back" once in a while. Even a slight change of perspective can make the world of difference.

I recently had the opportunity to do some freelance work that would have been paid in cryptocurrency and your book was one of the first resources that I referenced to get my head around all that was involved. Your book is comprehensive and easy to read and the typography and layout add to the value.

I see that you are dealing with your burnout and depression, especially since you are actively writing about it. That is all positive! Having seen the response from Hieu (@hieu-van), I felt compelled to "put pen to paper" (electronically) and to send you a few lines. Knowing that your work is appreciated will, I hope, add some fuel to the fire of your recovery.

Again, thanks for your comprehensive resource, and trusting that you will start to climb out of the valley in the days ahead.

With all best wishes and kind regards,
[Liam](https://github.com/treeman/why_cryptocurrencies/issues/43)

**Comment by treeman** [comment]
Thank you both, I really appreciate it. I also wrote a few words about my burnout [on my blog](https://www.jonashietala.se/blog/2023/03/14/battling_burnout/) if you're interested.
